version: '3'

services:
  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_DATABASE: le_barbz_db
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: spring
      MYSQL_PASSWORD: spring_password
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: db_admin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    restart: always
    ports:
      - 8081:80
